# -*- coding: utf-8 -*-
"""Homework_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDBm3RWocnIb8ppV-RiFe8BZ3mowJQj-
"""

import numpy as np
import pandas as pd

np.__version__

df = pd.read_csv("data.csv")

df.shape

result = df.groupby('Make').size().sort_values()

result

df.Make.nunique()

answer = df[df['Make'] == 'Audi'].nunique()

answer

df.isnull().sum()

df.head(3)

df.isnull().sum()

df['Engine Cylinders'].median()

f = df['Engine Cylinders'].mode()

f

df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)

df['Engine Cylinders'].median()

#number 8
df2 = df[df['Make'] == 'Lotus']

df2 = df2[["Engine HP", "Engine Cylinders"]].drop_duplicates()

df2

X = df2.values

X

XT = X.T

XTX = XT.dot(X)

XTX

XTX_invert = np.linalg.inv(XTX)

y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

w = (XTX_invert.dot(XT)).dot(y)

w